### ISSUE TITLE
App Folders not created correctly

### ISSUE THREAD

**Issue by Viixy** [ryancbutler/XDReplicate#7]
Application folders created but only first character, e.g. folder "Windows" on export results in folder "W" on import.

**Comment by ryancbutler** [comment]
Interesting.  I just ran a test on 7.14 with the following structure and it created successfully.
* Applications
   * Windows
       *  Test 1 
       *  Test 2

What version of XD are you running?  And can you provide your folder structure?

**Comment by Viixy** [comment]
I am using 7.12, and the folder structure is extremely simple:

\
\Apps

I will try upgrading the lab environment to 7.14 and see if the issue resolves.

**Comment by Viixy** [comment]
I have same result using 7.14 too. Strange.

**Comment by ryancbutler** [comment]
Can you run Get-BrokerAdminFolder on your source site?

**Comment by ryancbutler** [comment]
@Viixy when you get a chance can you grab the latest copy of the script and try again?  I cleaned up how the folders are created and hopefully works for you now.  If it doesn't please include the get-brokeradminfolder output of the source and destination.

**Comment by ryancbutler** [comment]
closing for now
