### ISSUE TITLE
Folders still do not work

### ISSUE THREAD

**Issue by Spontrel** [ryancbutler/XDReplicate#8]
After making an export, on the import, folders are not made correctly.  The script will properly create any delivery group that does not exist, so that works great.  If there are no pre-existing folders (the delivery group exists, but it is empty), the script will build only the first letter of each folder.  After making the first letter of each folder, it will import apps in to the folder root, not the folder names where the apps should go.  If I pre-create folder names, the script will initially build the apps in the correct locations, but will not assign permissions (you get an error on each permission setting attempt).  If I re-run the same script, on the second time it is run, it fixes the permissions.

I think the problem might be in how the data is exported more than how the import is handling it.

We really need a script like this to work for our pod design.  We want to replicate certain delivery groups to each prod and make sure they are all exactly the same.

**Comment by Spontrel** [comment]
Creating App
Processing AMALGA\
FOLDER NOT FOUND
Creating folder
Processing A\
FOLDER FOUND
Setting App Permissions

in this example, it finds there is an Amalga folder in the export, but it will create a folder named A

If I pre-build AMALGA, it will place the apps in there, but it will not set permissions correctly.  This is the result:


Proccessing App AMALGA Apps
Creating App
Processing AMALGA\
FOLDER FOUND
Setting App Permissions
MYDOMAIN\our_techs
Add-BrokerUser : Application not found
At \\MYDOMAIN\XDReplicate_6-27-17.ps1:485 char:17
+                 Add-BrokerUser -AdminAddress $xdhost -Name $user -Application $a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Add-BrokerUser], SdkOperationException
    + FullyQualifiedErrorId : Citrix.XDPowerShell.Broker.UnknownApplication,Citrix.Broker.Admin.SDK.AddBrokerUserCommand

**Comment by ryancbutler** [comment]
Gah! I can not replicate this on my end.  Looks like the line numbers aren't quite matching up to what I have.  Do you have version 1.2.3?  If so can you give the exact folder structure you are working with?  Are you exporting to XML or doing both right from the script? Are you pushing to a another DDC or pulling from?

**Comment by Spontrel** [comment]
I realized I may be part of the problem with trying this between sites that are not the same XA version.  I will test again and see if it just starts working.  If I get failures, I'll post all the details about it I can find.  Yes, I'm exporting the XML from the script on the source server, and I am doing a pull from the target server.  Both are on the same domain.  I'll post results when I get them re-tested.

**Comment by Spontrel** [comment]
Ryan, 
It took a while to get the site upgrades done.  Lots of problems with SmartMigrate from Citrix to 7.14.1, so I had to open tickets, etc.  Finally I have new 7.14.1 sites and applications there to migrate between pods.  

Starting position:  Site 1 has apps, Site 2 is empty completely.  No App folders, no Delivery Groups

Folder Creation issue:  Solved.  Migrating to 7.14.1 for source and target site solved the strange folder creation issues.  

User Creation issue:  Not solved:

::: If it finds a folder (in this case this is the root Applications folder), it works great and it creates both the app and the user accounts associated.

However, if the folder is new, and the app must be created, it cannot figure out how to add user accounts to the app.  Below is a capture of the progress.  Note:  If you re-run the app,  it works mostly.  It will fix the permissions it finds missing.  I will open a new comment window for the second pass errors.
::::

Proccessing App Citrix AppCent
Creating App
Processing 
FOLDER FOUND
Setting App Permissions
MyDomain\My_Account
Proccessing App ScriptedImages Push
Creating App
Processing TEAM Troubleshooting\Apps\
FOLDER NOT FOUND
Creating folder
Processing TEAM Troubleshooting\
FOLDER NOT FOUND
Processing TEAM Troubleshooting\Apps\
FOLDER NOT FOUND
Setting App Permissions
MyDomain\AnotherAccount
Add-BrokerUser : Application not found
At \\MyDomain\TEAM\scripts\citrix\XA7_replication\XDReplicate_6-27-17.ps1:485 char:17
+                 Add-BrokerUser -AdminAddress $xdhost -Name $user -Application $a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Add-BrokerUser], SdkOperationException
    + FullyQualifiedErrorId : Citrix.XDPowerShell.Broker.UnknownApplication,Citrix.Broker.Admin.SDK.AddBrokerUserCommand
 
MyDomain\My_Account
Add-BrokerUser : Application not found
At \\MyDomain\TEAM\scripts\citrix\XA7_replication\XDReplicate_6-27-17.ps1:485 char:17
+                 Add-BrokerUser -AdminAddress $xdhost -Name $user -Application $a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Add-BrokerUser], SdkOperationException
    + FullyQualifiedErrorId : Citrix.XDPowerShell.Broker.UnknownApplication,Citrix.Broker.Admin.SDK.AddBrokerUserCommand

**Comment by Spontrel** [comment]
Second item:  This script does not handle the Command Line Argument of an application.  
An example is one of our apps that hast this command line argument:
"-noexit \\MyDomain\scripts\citrix\push-Images.ps1"  The script can't handle the -no exit part because it is not parsing the export correctly

Setting App Permissions
AMC\MyGroup
Proccessing App dImages Push
Setting App
In correct folder
Set-BrokerApplication : A parameter cannot be found that matches parameter name 'noexit'.
At line:1 char:112
+ ... ineArguments ""-noexit \\MyDomain\citrix\push-Images.ps1"" -CommandLine ...
+                    ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-BrokerApplication], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Citrix.Broker.Admin.SDK.SetBrokerApplicationCommand
 
Icons Match

**Comment by ryancbutler** [comment]
Thanks for the feedback.  Going to create separate issues for each issue and close this one
