### ISSUE TITLE
Command line arguments don't like certain quotes or hyphens

### ISSUE THREAD

**Issue by ryancbutler** [ryancbutler/XDReplicate#9]
From issue #8 
>  Second item:  This script does not handle the Command Line Argument of an application.  
> An example is one of our apps that hast this command line argument:
> "-noexit \\MyDomain\scripts\citrix\push-Images.ps1"  The script can't handle the -no exit part because it is not parsing the export correctly
> 
> Setting App Permissions
> AMC\MyGroup
> Proccessing App dImages Push
> Setting App
> In correct folder
> Set-BrokerApplication : A parameter cannot be found that matches parameter name 'noexit'.
> At line:1 char:112
> + ... ineArguments ""-noexit \\MyDomain\citrix\push-Images.ps1"" -CommandLine ...
> +                    ~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Set-BrokerApplication], ParameterBindingException
>     + FullyQualifiedErrorId : NamedParameterNotFound,Citrix.Broker.Admin.SDK.SetBrokerApplicationCommand
>  
> Icons Match

**Comment by ryancbutler** [comment]
This is a more difficult to fix than I thought.  During testing if I pass the variable with double quotes and includes a hyphen it will fail.  Going to have to include more syntax to work around arguments with quotes, without quotes and hyphens it seems.  For now the script does **NOT** include quotes which seems to work with hyphens.

**Comment by ryancbutler** [comment]
Hopefully this is fixed.  Had to play around with how the strings are handled since some have quotes and some don't. fc82823590768ff6612083323373f30a98f560a6 (1.2.5)  Let me know if this works.

**Comment by Spontrel** [comment]
Fixed.  Thanks!

**Comment by ryancbutler** [comment]
:+1: closing issue
